### PR TITLE
carthage support 

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @AndrewSB! Thank you so much for the PR, I really appreciate it! 🎉 We just need an entry in the [Changelog](https://github.com/sunshinejr/RxPermission/blob/master/Changelog.md) and we are ready to merge! If you don't have time for it, don't worry, I can do it for you. :bow:

**Comment by AndrewSB** [comment]
@sunshinejr done!

**Comment by sunshinejr** [comment]
💯 thanks again!

**Comment by delba** [comment]
🎉 Thanks !

**Pull request merged**
