### PR TITLE
add property to get permission status as Observable;

### PR DESCRIPTION
**Pull request by tomisacat**

### CODE REVIEW

**Comment by AndrewSB** [comment]
Hey @tomisacat, thank you for suggesting this addition!! Can you help me understand what the value of this is? I must be misunderstanding your use case, I don't understand why one would want to wrap a synchronous property in an Observable.

**Comment by tomisacat** [comment]
Hey @AndrewSB There exists such scenario: show the origin permission state(maybe .notDetermined) and not roughly show an alert to grant authorization, but when user want to do something related this permission(like access to Photo Library), manually grant the permission.

**Comment by AndrewSB** [comment]
@tomisacat that use case makes sense, but why add the `Observable<PermissionStatus>` instead of doing something like `Observable.just(permissionStatus)` in your product?

**Comment by tomisacat** [comment]
@AndrewSB They're almost identical as `.just` operator send `.next` and followed `.completed` event just like my extension, but your solution seems  more elegant without any change : )

**Comment by AndrewSB** [comment]
I'm happy we came to an understanding 😄

If you ever have other changes that you think would be nice for the project, don't hesitate to create an Issue/PR!

**Pull request closed without merging**
