### PR TITLE
Update RxSwift version

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by sunshinejr** [comment]
Thank you so much Andrew! 💯

**Comment by AndrewSB** [comment]
My pleasure 🙃

Off topic: I was reading a blog post you wrote about rxswift, and you said
you'd write about a neat micro library for us handling disposables and a
disposeBag.
Did you ever write that post?

**Comment by sunshinejr** [comment]
@AndrewSB nope :< No time at all for blog posts lately, would love to be back on it tho.

**Comment by AndrewSB** [comment]
I feel, I want to start writing, but Im trying to grind out two releases before I set some time aside -- really hoping that doesn't mean I'm going to put it off for ages 😦

What is the micro library for managing `disposeBag`s that you were going to talk about?

**Pull request merged**
